### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by canao** [lejsue/symbols-navigator#1]
Thanks for nice package.

I use atom for mac.
I got an error because I don't have permission to execute the following files.

```
/packages/symbols-navigator/vendor/universal-ctags-darwin
```

I solved it by executing the following command.

```
chmod +x universal-ctags-darwin
```

Would you consider examining correspondence in the next version.

----------------------------------------
[Enter steps to reproduce below:]

1. Open any file

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [symbols-navigator](https://github.com/lejsue/symbols-navigator) package 1.0.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:392

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:321:63)
    at BufferedProcess.start (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:127:20)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:112:18)
    at /packages/symbols-navigator/lib/tag-generator.js:132:14
    at TagGenerator.generate (/packages/symbols-navigator/lib/tag-generator.js:118:12)
    at SymbolsNavigatorView.generateTags (/packages/symbols-navigator/lib/symbols-navigator-view.js:97:53)
    at /packages/symbols-navigator/lib/symbols-navigator-view.js:63:14
    at SymbolsNavigatorView.populate (/packages/symbols-navigator/lib/symbols-navigator-view.js:80:9)
    at /packages/symbols-navigator/lib/symbols-navigator-view.js:39:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:478:28)
    at Dock.subscriptions.CompositeDisposable.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/src/dock.js:58:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:264:24)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:911:20)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1165:20)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
```

### Commands

```
     -0:06.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

**Comment by lejsue** [comment]
Hi canao,

Thanks for using this package and reporting this bug. 
I really lost its permission setting. lol
I'll try to fix it in next release.
