### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by mikebronner** [lejsue/symbols-navigator#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [symbols-navigator](https://github.com/lejsue/symbols-navigator) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At /Users/mike/.atom/packages/symbols-navigator/lib/tree-view.js:231

TypeError: Cannot read property 'classList' of null
    at TreeView.onClick (/packages/symbols-navigator/lib/tree-view.js:231:44)
    at /packages/symbols-navigator/lib/tree-view.js:120:12)
```

### Commands

```
  5x -0:08.2.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
close-on-left 0.9.2 
dash 1.7.1 
double-tag 1.1.0 
duotone-light-syntax 2.1.0 
file-icons 2.1.15 
highlight-selected 0.13.1 
intentions 1.1.5 
language-blade 0.38.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
open 0.1.1 
pen-paper-coffee-syntax 0.14.9 
php-hyperclick 1.2.1 
platformio-ide-terminal 2.7.0 
recent-files-fuzzy-finder 0.4.0 
sort-lines 0.18.0 
symbols-navigator 1.3.0 
sync-settings 0.8.3 
tag 0.5.0 
tester 1.4.0 
tester-phpunit 1.0.6 
wakatime 7.0.4 
zentabs 0.8.9 
```

**Comment by lejsue** [comment]
Hi, thanks for this bug. Let me fix it!
